### ISSUE TITLE
This project is great. i want to know how to use usecase

### ISSUE THREAD

**Issue by est7** [okaryo/CleanArchitectureTodoAppTrainingWithFlutter#41]
My code is like this
```
class InitChatListUsecase {
  final IChatRepository repository;

  InitChatListUsecase({required this.repository});

  Future<Result<List<ChatModel>>> call() {
    return repository.getAllChatList();
  }
}
```
 The code in the project looks like this
```
@riverpod
class DeleteTodoUseCaseImpl extends _$DeleteTodoUseCaseImpl
    implements DeleteTodoUseCase {
  @override
  Future<void> build(final int id) {
    final TodosRepository repository =
        ref.read(todosRepositoryImplProvider.notifier);
    return repository.deleteTodo(id);
  }
}
```

I want to know why Usecase is used as “StateNotifier” ?I'm a fresh on Riverpod, hope you can tell me about it

**Comment by okaryo** [comment]
I believe this code is from one of the forks of the repository, so I'm not sure of the exact intention behind it. Based on the mention of `@riverpod`, it seems that `riverpod_generator` is being used, and therefore `StateNotifier` is being used within the UseCase. I cannot say for certain as I have not personally used `riverpod_generator`, so please keep that in mind.

https://pub.dev/packages/riverpod_generator
